// This file is part of pallet-ema-oracle.

// Copyright (C) 2022  Intergalactic, Limited (GIB).
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_ema_oracle
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-08-31, STEPS: 20, REPEAT: 10, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/basilisk
// benchmark
// --execution
// wasm
// --wasm-execution
// compiled
// --chain
// dev
// --pallet
// pallet-ema-oracle
// --extrinsic
//
// --steps
// 20
// --repeat
// 10
// --template
// .maintain/pallet-weight-template.hbs
// --output
// weights.rs
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_ema_oracle.
pub trait WeightInfo {
    fn on_finalize_no_entry() -> Weight;
    fn on_finalize_multiple_tokens(b: u32) -> Weight;
    fn on_trade_multiple_tokens(b: u32) -> Weight;
    fn on_liquidity_changed_multiple_tokens(b: u32) -> Weight;
    fn get_entry() -> Weight;
}

pub struct BasiliskWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for BasiliskWeight<T> {
    fn on_finalize_no_entry() -> Weight {
        (6_402_000 as Weight).saturating_add(T::DbWeight::get().reads(1 as Weight))
    }
    fn on_finalize_multiple_tokens(b: u32) -> Weight {
        (826_827_000 as Weight) // Standard Error: 1_128_000
            .saturating_add((92_477_000 as Weight).saturating_mul(b as Weight))
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().reads((4 as Weight).saturating_mul(b as Weight)))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
            .saturating_add(T::DbWeight::get().writes((4 as Weight).saturating_mul(b as Weight)))
    }
    fn on_trade_multiple_tokens(b: u32) -> Weight {
        (66_977_000 as Weight) // Standard Error: 12_000
            .saturating_add((824_000 as Weight).saturating_mul(b as Weight))
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn on_liquidity_changed_multiple_tokens(b: u32) -> Weight {
        (60_087_000 as Weight) // Standard Error: 12_000
            .saturating_add((839_000 as Weight).saturating_mul(b as Weight))
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn get_entry() -> Weight {
        (165_684_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn on_finalize_no_entry() -> Weight {
        (6_402_000 as Weight).saturating_add(RocksDbWeight::get().reads(1 as Weight))
    }
    fn on_finalize_multiple_tokens(b: u32) -> Weight {
        (826_827_000 as Weight) // Standard Error: 1_128_000
            .saturating_add((92_477_000 as Weight).saturating_mul(b as Weight))
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().reads((4 as Weight).saturating_mul(b as Weight)))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes((4 as Weight).saturating_mul(b as Weight)))
    }
    fn on_trade_multiple_tokens(b: u32) -> Weight {
        (66_977_000 as Weight) // Standard Error: 12_000
            .saturating_add((824_000 as Weight).saturating_mul(b as Weight))
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
    }
    fn on_liquidity_changed_multiple_tokens(b: u32) -> Weight {
        (60_087_000 as Weight) // Standard Error: 12_000
            .saturating_add((839_000 as Weight).saturating_mul(b as Weight))
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
    }
    fn get_entry() -> Weight {
        (165_684_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
}
